# [INFO] Kubernetes Yaml to Pulumi
> https://github.com/pulumi/kube2pulumi
 
# [ERROR] `error: [409] Conflict: Another update is currently in progress.`
이유는 둘 중 하나다.
1. 현재 누군가 같은 stack에서 업데이트 중
2. pulumi CLI에서 충돌이 발생
2번의 경우엔 `pulumi cancel`로 업데이트를 취소한다.

# [ERROR] `CREATE DATABASE permission denied in database 'master'. unable to get the permission`
- 상황 : `create database ..`중에 발생
- 해결 : 권한이 없어서 발생하는 오류이다. 관리자 권한으로 들어가거나 현재 계정을 sysadmin으로 바꾼다.

> https://dba.stackexchange.com/questions/78388/create-database-permission-denied-in-database-master-unable-to-get-the-permis

# [INFO] EventBridge로 AWS Lambda 함수 스케줄링( feat. Pulumi
[Schedule AWS Lambda functions using EventBridge](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-run-lambda-schedule.html)를 참고하면 아래 예시와 같다.
1. EventRule 생성 : `aws events put-rule --name my-scheduled-rule --schedule-expression 'rate(5 minutes)'`
2.  lambda에 permission 추가
```
aws lambda add-permission \
--function-name LogScheduledEvent \
--statement-id my-scheduled-event \
--action 'lambda:InvokeFunction' \
--principal events.amazonaws.com \
--source-arn arn:aws:events:us-east-1:123456789012:rule/my-scheduled-rule
```
3. EventTarget 설정 : `aws events put-targets --rule my-scheduled-rule --targets file://targets.json`

### pulumi로 변환 

```python
handler =aws.lambda_.Function(
				resource_name=resource_name + "-function",
				name = resource_name,
				package_type = "Image",
				role = role.arn,
				image_uri = IMAGE,
				timeout=120 # 2min
				)
schedule = aws.cloudwatch.EventRule(
        resource_name + "-schedule",
        name = resource_name + "-schedule",
        schedule_expression = "rate(15 minutes)"
    )

aws.lambda_.Permission(
		resource_name+"-event-permisson",
		function=handler.name,
		statement_id="schedule-event",
		action="lambda:InvokeFunction",
		principal="events.amazonaws.com",
		source_arn=schedule.arn
		)
aws.cloudwatch.EventTarget(
resource_name+"-trigger",
arn=handler.arn,
rule=schedule.name
)
```

# [INFO] EBS 볼륨 확장
> https://aws.amazon.com/ko/premiumsupport/knowledge-center/extend-linux-file-system/

# [ERROR] `resize2fs: Device or resource busy while trying to open /dev/xvda`
> [볼륨 크기 조정 후 Linux 파일 시스템 확장](https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.html#extend-linux-volume-partition)

```
$ lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme0n1       259:0    0  100G  0 disk 
├─nvme0n1p1   259:1    0    8G  0 part /
└─nvme0n1p128 259:2    0    1M  0 part 
```
- `/dev/nvme0n1`에는 `dev/nvme0n1p1`라는 파티션이 있다.

8G로 설정되어 있으므로 파티션 크기를 늘려줘야 한다.
```
$ sudo growpart /dev/nvme0n1 1
CHANGED: partition=1 start=4096 old: size=16773087 end=16777183 new: size=209711071 end=209715167
```
```
$ lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme0n1       259:0    0  100G  0 disk 
├─nvme0n1p1   259:1    0  100G  0 part /
└─nvme0n1p128 259:2    0    1M  0 part 
```
파티션 볼륨 크기가 확장되었다.

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  412K  3.9G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/nvme0n1p1  8.0G  1.9G  6.2G  23% /
tmpfs           787M     0  787M   0% /run/user/1000
```
-  볼륨에 대한 파일 시스템의 크기를 확인(`df -h`)해보면 원래 볼륨 크기인 8GB가 반영되어있다.

각 볼륨의 파일 시스템을 확장한다.
- [XFS 파일 시스템] : `xfs_growfs`
	```
	$ sudo xfs_growfs -d /
	```
- [ex4 파일 시스템] : `resize2fs`
	```
	$ sudo resize2fs /dev/nvme0n1p1
	$ sudo resize2fs /dev/nvme1n1
	```
	
파일 시스템의 볼륨이 확장되었다.
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  412K  3.9G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/nvme0n1p1  100G  1.9G   99G   2% /
tmpfs           787M     0  787M   0% /run/user/1000
```
